store HelloWorld.ts to pharo's file browser

Open Pharo -> Tools -> transcript -> Enter "HelloWorld new print" -> select all your enter message -> right click -> Do it

store P2_MyIf.ts to pharo's file browser

Open Pharo -> Tools -> transcript -> Enter "P2_MyIf new IfPrint" -> select all your enter message -> right click -> Do it

store P2_feature.ts to pharo's file browser

Open Pharo -> Tools -> transcript -> Enter "P2_feature new DoYourThing" -> select all your enter message -> right click -> Do it

store P3_feature.ts to pharo's file browser

Open Pharo -> Tools -> transcript -> Enter "P3_feature new P3_content" -> select all your enter message -> right click -> Do it

store P3_array.ts to pharo's file browser

Open Pharo -> Tools -> transcript -> Enter "P3_array new Array" -> select all your enter message -> right click -> Do it

store P4_feature.ts to pharo's file browser

Open Pharo -> Tools -> transcript -> Enter "P4_feature new Dog" -> select all your enter message -> right click -> Do it

(If you can not open p5_collection directly.)
Select all code in P5_collection -> copy it -> open pharo -> tools -> playground -> paste -> green play button.


