store HelloWorld.ts to pharo's file browser

Open Pharo -> Tools -> transcript -> Enter "HelloWorld new print" -> select all your enter message -> right click -> Do it

store P2_MyIf.ts to pharo's file browser

Open Pharo -> Tools -> transcript -> Enter "P2_MyIf new IfPrint" -> select all your enter message -> right click -> Do it

store P2_feature.ts to pharo's file browser

Open Pharo -> Tools -> transcript -> Enter "P2_feature new DoYourThing" -> select all your enter message -> right click -> Do it
